# Generated by Django 5.0.7 on 2026-09-07 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_popular', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Seat categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('facilities', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cinemas', to='cinemas.city')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('supported_formats', models.JSONField(default=list)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='cinemas.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(max_length=2)),
                ('seat_number', models.PositiveSmallIntegerField()),
                ('is_aisle_start', models.BooleanField(default=False)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinemas.screen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinemas.seatcategory')),
            ],
            options={
                'ordering': ['row_label', 'seat_number'],
            },
        ),
        migrations.AddIndex(
            model_name='cinema',
            index=models.Index(fields=['city'], name='cinemas_cin_city_id_6b1e74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together={('cinema', 'name')},
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['screen'], name='cinemas_sea_screen__e1f6ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('screen', 'row_label', 'seat_number')},
        ),
    ]
