# Generated by Django 5.0.7 on 2026-09-07 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(choices=[('popcorn', 'Popcorn'), ('nachos', 'Nachos'), ('beverage', 'Cold Drinks'), ('water', 'Water'), ('combo', 'Combo'), ('snack', 'Snacks')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('inventory_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=7)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='bookings.booking')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.fooditem')),
            ],
        ),
    ]
