# Generated by Django 5.0.7 on 2026-09-07 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='events.eventschedule'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='events.eventschedule'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='events.tickettier'),
        ),
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='cinemas.city'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='events.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='tickettier',
            unique_together={('schedule', 'name')},
        ),
        migrations.AddIndex(
            model_name='eventbooking',
            index=models.Index(fields=['user', '-created_at'], name='events_even_user_id_900c65_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['city'], name='events_venu_city_id_2fcfef_idx'),
        ),
        migrations.AddIndex(
            model_name='eventschedule',
            index=models.Index(fields=['event', 'date'], name='events_even_event_i_113b4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventschedule',
            unique_together={('venue', 'date', 'start_time')},
        ),
    ]
