# Generated by Django 5.0.7 on 2026-09-07 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
        ('shows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='showseat',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_seats', to='cinemas.seat'),
        ),
        migrations.AddField(
            model_name='showseat',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_seats', to='shows.show'),
        ),
        migrations.AddField(
            model_name='showseatprice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinemas.seatcategory'),
        ),
        migrations.AddField(
            model_name='showseatprice',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shows.show'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['movie', 'date'], name='shows_show_movie_i_731c5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('screen', 'date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['show', 'status'], name='shows_shows_show_id_154d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['status', 'locked_until'], name='shows_shows_status_676701_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='showseat',
            unique_together={('show', 'seat')},
        ),
        migrations.AlterUniqueTogether(
            name='showseatprice',
            unique_together={('show', 'category')},
        ),
    ]
